#!/bin/bash

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/Vundle.vim

VIMRC=~/.vimrc

if [ -f $VIMRC ];
then
   mv $VIMRC $VIMRC.bak
fi

mv ~/.vimrc ~/.vimrc.bak
ln -s ~/.vim/vimrc ~/.vimrc

sudo apt-get install language-pack-en silversearcher-ag Ctags
sudo update-locale LANG=en_US.UTF-8

vim +PluginInstall +qall
